---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  dependsOn:
    - name: infra-config
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-config
  path: ./apps/dev
  prune: true
  validation: server
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v1beta1
      kind: HelmRelease
      name: ingress-nginx
      namespace: ingress-nginx
