---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infra-config
  namespace: flux-system
spec:
  dependsOn:
    - name: infra
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-config
  path: ./infra/config
  prune: true
  validation: server
