---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: fred
spec:
  interval: 5m
  chart:
    spec:
      # Source:
      chart: charts/fred
      version: 0.1.0
      sourceRef:
        kind: GitRepository
        name: flux-config
        namespace: flux-system
      valuesFile: charts/fred/values.yaml
