---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  interval: 5m
  chart:
    spec:
      # Source: https://github.com/jetstack/cert-manager/blob/master/deploy/charts/cert-manager/Chart.template.yaml
      chart: cert-manager
      version: v1.7.1
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: cert-manager
  install:
    createNamespace: true
  values:
    # Source: https://github.com/cert-manager/cert-manager/blob/master/deploy/charts/cert-manager/values.yaml
    installCRDs: true

