---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: fred
spec:
  interval: 5m
  chart:
    spec:
      # Source:
      chart: charts/fred
      version: 0.1.0
      sourceRef:
        kind: GitRepository
        name: flux-config
        namespace: flux-system
  values:
    image:
      tag: fred-pirate
      # Available tags:
      # fred
      # frida
      # fred-xmas
      # fred-pirate
      # fred-cap
      # fred-easter
    ingress:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
      hosts:
        - host: demo.devops.whiteduck.de
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - secretName: demo.devops.whiteduck.de
          hosts:
            - demo.devops.whiteduck.de
